// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB57twzBwvBQAUwm8cbsadvn-p7VuUV1jA',
    appId: '1:797302934613:web:8bb39f6eb4ea988f59d8dc',
    messagingSenderId: '797302934613',
    projectId: 'ecommerce-flutter-72e6f',
    authDomain: 'ecommerce-flutter-72e6f.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-72e6f.appspot.com',
    measurementId: 'G-E5C1FZ4FM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXwjXOS7IAhqZmA5w5RKHwir1Ig1PPlS0',
    appId: '1:797302934613:android:0a67c7d594178b6559d8dc',
    messagingSenderId: '797302934613',
    projectId: 'ecommerce-flutter-72e6f',
    storageBucket: 'ecommerce-flutter-72e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvPFxjCkddZMwIaAnpylhZDZRmVSBHOog',
    appId: '1:797302934613:ios:4c212cb7dfaafd6c59d8dc',
    messagingSenderId: '797302934613',
    projectId: 'ecommerce-flutter-72e6f',
    storageBucket: 'ecommerce-flutter-72e6f.appspot.com',
    iosClientId: '797302934613-p000otunntens6kbti4d89ll9p5kk8b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
